name: file_handeling
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_screenutil: ^5.9.3
  get_it: ^9.0.5
  go_router: ^17.0.0
  supabase_flutter: ^2.10.3
  bloc: ^9.1.0
  injectable: ^2.6.0
  fpdart: ^1.2.0
  dart_mappable: ^4.6.1
  pinput: ^5.0.2
  pdfrx: ^2.2.12
  file_picker: ^10.3.6
  result_dart: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.9.1
  build_runner: ^2.10.2
  dart_mappable_builder: ^4.6.1


flutter:
  uses-material-design: true
  assets:
  - .env
  - assets/